seed: 32
use_mlflow: True
data_dir: data/czii-cryo-et-object-identification/train

model:
  backbone: UNet
  num_classes: 7

train_params:
  epochs: 1000
  eval_frequency: 2
  patience: 20
  channels: [32,64,128,256,512]
  strides: [2,2,2,2]
  num_res_units: 2
  alpha: 0.05
  beta: 0.95


optimizer:
  name: Adam
  lr: 1e-3

outputs:
  model_dir: models/baseline

config_blob: configs/config_blob_v1.0.json